== Three Steps of a Change Agent 

*Welcoming Reality - The Furious Indifference to Our Cause*

For all my talk, I weekly come back to the question "So how do we put this into effect here where I work?" It
is not uncommon for those in IT to rarely see the ideal solution, method or process actually put into practice.

Recently I've seen the confluence of, at first glance, unrelated items. When seen holistically, though, these
items point to what I feel is at the heart of leading change in the workplace.

*You Need to Fight, but Fight Right*

_"A soldier surrounded by enemies, if he is to cut his way out, needs to combine a strong desire"_

In business terms, a leader is surrounded by all the reasons things don't change in their workplace. If he is to succeed in making a difference, he needs to combine a strong desire to keep his job and favor with his boss
and colleagues with a strange carelessness about being fired. He must not merely worry about keeping his job
and what those in influential positions think of him, for then he will be a coward, fearful, and he will not make a difference. He must not merely wait to be fired - saying things and taking actions that communicate not
caring about being fired or about what his boss or those in influential positions think of him, for then he will be fired and he will not make a difference. He must seek to make a difference in a spirit of furious indifference to whether he actually succeeds in creating change.

First, we must decide that we're going to fight to make a difference. This is the "strong desire for living."
Making a difference takes effort, commitment, determination, and often much more physically and emotionally
exhausting than just accepting a substandard environment.

Second, we realize and accept that making a difference is a desire, not a goal. Desires are what we strive for, goals are what we can actually achieve. Often, people and circumstances get in the way of what we hope to
achieve. If they get in the way of goals, we can become frustrated, angry, resentful. With desires, it is easier to accept failing to attain the end result in its entirety - not getting closure. This helps one to keep from reacting. Instead, they respond. The focus is on the action(s) or logical argument(s) in question positions being discussed, not the people themselves having the dialog.

Third, we find a way to put ourselves second to the cause and the possible consequences of advocating the
cause. This is the "strange carelessness about dying." We stop looking out for "#1" - ourselves, as paramount.
I haven't found a way to be effective in making a difference when I am thinking of myself first because I keep
getting in the way. That is, while trying to convince someone of my point, fear and doubt keep me thinking in
the back of my mind, "What if they think this is a truly bad idea? If they did, would they communicate that to
my boss? What then would he think of me?" At times, I become competitive. I approach discussions where a
decision outcome will occur as a zero-sum game where if I don't win, I'll lose. In these cases, I must win
"A soldier surrounded by enemies, if he is to cut his way out, needs to combine a strong desire for living
because if I don't, I'll appear weak, foolish, less-than, that my ideas aren't sound. This emotional reaction can be especially strong in a public forum, such as meeting or an email thread with many recipients.

These three points are simple, but not easy. Making a change to the way things are done involves other
people. We are interdependent in all but the smallest IT organizations. And it is our interactions and
relationships with these people (and their attitudes, beliefs, understanding, motives, agendas) that are
principally the challenge.

*If You Want a Queen, You Have to Be a King*

There's a saying in courtship that if you want a Queen, you have to be a King. This means that if we want a
certain reality, we have to be the type of person deserving of that reality. We have to be a person of character if we are to expect a working environment where there is good, healthy interdependence and commonality.

_"Creating the unity necessary to run an effective business... Requires great personal strength and courage. In addition, we can see on an even deeper level that effective interdependence can only be achieved."_

The combination of these two quotes from recent reading and my concerns on how to truly create change in
our IT department occurred as I reviewed a document this week. It was a going-away present for a coworker.
This coworker is widely viewed as an exceptional and very well respected senior level developer in our
organization. The gift was a list comprised of individual submissions from his colleagues of the positive traits they saw in him. For all his wealth of technical and intellectual talent, by far the most common items in the list were "patience", "persistence", "friendly", "helpful", "giving." After working alongside him for a year, I had been mistaking the dominant reason he was so effective. It was because of his character, who he is. He was a great worker because he was a great person.

To be change agents, we need to commit to the cause, let ourselves be second, hold on to what we want with
open hands, and have the kind of character which nourishes good relationships (and effectiveness) with our
coworkers.

.About the Author
[NOTE]
****
Name:: Scott Dunn
Biography:: 
****
