== Fooing the Bar

I'm afraid I still don't understand, sir. Mr. Worf, you do remember how to fire phasers? When has justice ever been as simple as a rule book? Yes, absolutely, I do indeed concur, wholeheartedly! The Federation's gone; the Borg is everywhere! How long can two people talk about nothing? The Enterprise computer system is controlled by three primary main processor cores, cross-linked with a redundant melacortz ramistat, fourteen kiloquad interface modules. A lot of things can change in twelve years, Admiral. You did exactly what you had to do. You considered all your options, you tried every alternative and then you made the hard choice. Now we know what they mean by 'advanced' tactical training. Congratulations - you just destroyed the Enterprise. Is it my imagination, or have tempers become a little frayed on the ship lately? and attack the Romulans. Maybe we better talk out here; the observation lounge has turned into a swamp. I am your worst nightmare!

You bet I'm agitated! I may be surrounded by insanity, but I am not insane. This should be interesting. Talk about going nowhere fast. I suggest you drop it, Mr. Data. The unexpected is our normal routine. Could someone survive inside a transporter buffer for 75 years? My oath is between Captain Kargan and myself. Your only concern is with how you obey my orders. Or do you prefer the rank of prisoner to that of lieutenant? Shields up! Rrrrred alert! We finished our first sensor sweep of the neutral zone.
