[[contributor_guidelines]]
== Contributor Guidelines

Each contributor is asked to provide one or more items (tips or bits of wisdom) that each have a title and associated discussion. 

Please read the sample contribution.:: 
   Already mentioned, but please look at the <<sample_contribution, sample contribution>>. If you are unfamiliar with AsciiDoc markup, take a look at the underlying markup of the page. You may also want to look at the linkhttp://powerman.name/doc/asciidoc[AsciiDoc cheatsheet].

Creative Commons license.::
   All contributions made to this site are required to be made under the link::http://creativecommons.org/licenses/by/3.0/us/[Creative Commons Attribution 3.0 license]. This means that by making a content contribution, you are agreeing that it is licensed to us and to others under this license. If you do not want your content to be available under this license, you should not contribute it.

Your submission may not be accepted.::
   Be aware that we may not be able to accept your contribution.

Keep your title pithy and to the point.::
  The title should only be a 2 to 10 words long if possible and should summarize or capture the essence of the advice. In print, we want each contribution to fit on a two-page spread. Keep your discussion between 400 and 500 words. Any contribution under 400 words is unlikely to make it to the Edited Contributions, let alone the book. And much more than 500 words will need to be edited down. There will be a limit on the maximum number of items that can be accepted from one author for the book (as yet to be decided, but probably 3 or 4), but there is currently no hard limit to the number of items that can be submitted to the site.

Edit your work only.::
   You have the ability to add or change your contributions at any time. To be a good participant, please edit your own contributions only. Be very careful that you don't accidentally alter someone else's work. You are, however, free to add comments on the discussion tab of any contribution. As editor, I will limit most of my editorial changes to basic copy editing (spelling, punctuation, grammar, and formatting). I will discuss any other suggestions or comments on a contributed item directly with its author.

Submit only your own work.::
   You warrant that all work that you contribute to this site is your original work, except for material that is in the public domain or for which you have obtained permission. Feel free to draw from your own existing work (blogs, articles, talks, etc.), so long as you are happy with the Creative Commons license.

Volunteers only.::
   Contributions are made on a volunteer basis — in other words, contributors are not paid for their contributions. The contributions will be made easily available to everyone on the World Wide Web for free. However, remember that those of you whose contributions are chosen for publication will get your name attached to your work, your bio published next to it, and a free copy of the published book. Any item you contribute you can also reuse in any form you wish, such as in a blog posting.

Free of commercials.:: 
   Please keep contributions free from references to specific products or technologies that compare their worth, or paint them in a positive or negative light.

Only submit a pull request when you consider your work complete.::
   Please submit your work once it is complete.  Once you make a pull request, the editor will review the submission and (possibly) suggest some changes.  Reducing work in progress makes it easier for you to see your own progress and for others to see the progress of the whole project.

Check spelling, word count, and formatting.::
   Such checking seems an obvious part of the professional attention to detail encouraged by the 97 Things books, but it is worth a reminder — sometimes it seems that it is honored more in the breach than in the observance. US spelling is used for the contributions, which should be between 400 and 500 words in length. Formatting can be checked using Show preview (but don't forget to Save page) or by looking at the saved page.

Remember to sign your work.::
   Your name and the rights message should appear at the bottom of each contribution. A contribution should be able to standalone, so having your name listed by a link on another page is of little use if someone arrives at the page via a more direct route.

Don't link to or discuss other contributions in your own contribution.::
   Each contribution is intended to be standalone. It should not require the reader to read anything else first or, if selected for the book, require the inclusion of another contribution.
