== It's Not Scrum, It's You

It's Not Scrum, It's You - Scott Dunn I was recently teaching a Certified Scrum Master class and was told by a student that Scrum didn't work because management still comes and demands additional features or projects and sets or keeps the deadlines and not asking for estimates of how long it will take.

That is not a Scrum problem. That's a business environment problem. And the solution is often the person lamenting it the most. Perhaps it's like the guy that complains about women because he is married to someone who makes demands and doesn't respect him. It's not women that's the problem, it's his allowing his wife to control him.

These are the type of complex organizational development problems that are difficult to solve. They take more than a two day class on Scrum fundamentals to solve. They may be very difficult and take a long time, but they are possible. Don't think that they are not. There is a world of difference in the mindsets behind possible and impossible.

If you fall into the trap that they are impossible, you give up trying - looking for possibilities, options, trying out new ideas. You lose hope. Certainly if you are a leader, it is incumbent upon you for the sake of the people who follow you. The book Strengths Based Leadership lists the four needs workers have of their leaders: hope, stability, compassion and trust. If you are an agilist, you are acting as a servant leader, and therefore need to maintain hope.

I couldn't tell this student how to solve his problem - that's contextual and that's why there are coaches helping organizations with these types of cultural and management changes. Even without a coach helping, there's a lot of places to look for good information on this.

But you won't take that first step if you are stuck thinking it's impossible.

.About The Author
[NOTE]
****
Author:: Scott Dunn
Biography::
****
