== 97 Things Every Agile Developer Should Know

Welcome to _97 Things Every Agile Developer Should Know_, pearls of wisdom for programmers collected from leading Agile practitioners.  There is no overarching narrative: The collection is intended simply to contain multiple and varied perspectives on what it is that contributors to the project feel programmers should know. This can be anything from code-focused advice to culture, from algorithm usage to agile thinking, from implementation know-how to professionalism, from style to substance, etc.

=== List of Contributors

Anyone who has https://github.com/oreillymedia/97-things-every-agile-developer-should-know/network/members[forked this project] is a potential contributor. Follow the link to the fork of another contributor to see the changes/updates. For example, click on any forked version of the book to see what the contributor is working on.
=== How to Contribute

If you are interested in contributing to the project, please review the following guidelines.

==== Read the contributor guidelines

The https://github.com/oreillymedia/97-things-every-agile-developer-should-know/blob/master/contributor_guidelines.asciidoc[Contributor Guidelines] has an overview of the style, length, format, and other details we're looking for from the contributions.  The tl;dr is:

* Use a conversational tone.  Be professional, not professorial.
* Submit 400–500 words.
* Include your name, a short biography, and a link to a photo of you that we'll use in the book.
* Be willing to work under a link::http://creativecommons.org/licenses/by/3.0/us/[Creative Commons Attribution 3.0 license].

==== Review the sample contribution

We've provided a https://github.com/oreillymedia/97-things-every-agile-developer-should-know/blob/master/SAMPLE_CONTRIBUTION.asciidoc[sample contribution] to provide an example of the what we're looking for, and to show you an example of what you will see when your are ready to add your own tip/axiom/pearl/guideline/contribution. Reading this example contribution won't take long, and is good practice.

==== Submit your contribution(s)

The https://github.com/oreillymedia/97-things-every-agile-developer-should-know/blob/master/submission_tutorial.asciidoc[Submission Tutorial] provides a step by step process for making a contribution.  The quick version is:

. Sign up for a GitHub account.
. Fork this repo to your new account.
. Add your contribution:
* Work in the master branch.
* Create a new file in the root directory that is based on your first name and last name with and extension of _.asciidoc_ (e.g., __mary_jones.asciidoc__).
* Write in http://powerman.name/doc/asciidoc[AsciiDoc].
* Include your name, bio, and link to an image of you that you'd like us to use in the book.
* Please don't edit other contributions.
. Submit a pull request when your contribution is as close to perfect as you can get it.

==== Engage with us in the discussion

Once we receive your pull request, we'll evaluate it for the book. The editor may ask you to make some modifications, so there will likely be some back and forth.  If we accept your contribution, we'll merge it into the master repository.
