== 97 Things Every Agile Developer Should Know

Welcome to the home page for the _97 Things Every Agile Developer Should Know_ project, pearls of wisdom for programmers collected from leading Agile practitioners.  There is no overarching narrative: The collection is intended simply to contain multiple and varied perspectives on what it is that contributors to the project feel programmers should know. This can be anything from code-focused advice to culture, from algorithm usage to agile thinking, from implementation know-how to professionalism, from style to substance, etc.

=== How to Contribute

If you are interested in contributing to the project, here's what you need to do.

==== Read the contributor guidelines.

The https://github.com/oreillymedia/97-things-every-agile-developer-should-know/blob/master/contributor_guidelines.asciidoc[Contributor Guidelines] has an overview of the style, length, format, and other details we're looking for from the contributions.  The tl;dr is:

* Conversational tone.  Be professional, not professorial.
* 400 - 500 words
* AsciiDoc format
* Short biography and a photo
* link::http://creativecommons.org/licenses/by/3.0/us/[Creative Commons Attribution 3.0 license]

==== Review the sample contribution

We've provided a https://github.com/oreillymedia/97-things-every-agile-developer-should-know/blob/master/SAMPLE_CONTRIBUTION.asciidoc[sample contribution] to provide an example of the what we're looking for, and to show you an example of what you will see when your are ready to add your own tip/axiom/pearl/guideline/contribution. Reading this example contribution won't take long, and is good practice.

==== Submit your contributions

The https://github.com/oreillymedia/97-things-every-agile-developer-should-know/blob/master/submission_tutorial.asciidoc[Submission Tutorial] provides a step by step process for making a contribution.  The quick version is:

* Sign up for a GitHub account
* Fork this repo to your new account
* Add your contribution
** Create a new file in the root directory that is based on your first name and last name with and extension of "asciidoc."  For example: "mary_jones.asciidoc"
** Write in http://powerman.name/doc/asciidoc[AsciiDoc] 
** Work in the master branch (we know this isn't ideal, but there it is)
** Don't edit other contributions
* Submit a pull request when your contribution is as close to perfect as you can get it
* Engage with the authors and editors in the pull request

==== Send us a pull request when your contribution is as close to perfect as you can get it.

Once we receive your pull request, we'll evaluate it for the book.  The editor might ask you to make some modifications, so there will likely be some back and forth.  If we accept your contribution, we'll merge it into the master repository.  