== 97 Things Every Agile Software Developer Should Know

Welcome to the home page for the _97 Things Every Agile Programmer Should Know_ project, pearls of wisdom for programmers collected from leading Agile practitioners.  There is no overarching narrative: The collection is intended simply to contain multiple and varied perspectives on what it is that contributors to the project feel programmers should know. This can be anything from code-focused advice to culture, from algorithm usage to agile thinking, from implementation know-how to professionalism, from style to substance, etc.

* <<contributor_guidelines,Contributor guidelines>>
* Contributor agreement

=== How to Contribute

==== Read the contributor guidelines.

The <<contributor_guidelines, Contributor Guidelines>> has an overview of the style, length, format, and other details we're looking for from the contributions.  The tl;dr is:
   * Conversational tone.  (professional, not professorial)
   * 400 - 500 words
   * AsciiDoc format
   * Short biography and a photo
   * link::http://creativecommons.org/licenses/by/3.0/us/[Creative Commons Attribution 3.0 license]

==== Review the sample contribution

We've provided a <<sample_contribution, sample contribution>> to provide an example of the what we're looking for, and to show you an example of what you will see when your are ready to add your own tip/axiom/pearl/guideline/contribution. Reading this example contribution won't take long, and is good practice.

==== Fork this repository and add your submission to the "contributions" directory.

If this  sounds like greek to you, then check out the <<submission_tutorial, Submission Tutorial>>.

==== Send us a pull request when your contribution is as close to perfect as you can get it.

Once we receive your pull request, we'll evaluate it for the book.  The editor might ask you to make some modifications, so there will likely be some back and forth.  If we accept your contribution, we'll merge it into the master repository.  